require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require 'pathname'

react_native_macos_absolute_path = File.dirname(
  `node --print "require.resolve('react-native-macos/package.json')"`.strip
)
react_native_macos_path = Pathname
  .new(react_native_macos_absolute_path)
  .relative_path_from(Pathname.new(__dir__))
  .to_s
require "#{react_native_macos_absolute_path}/scripts/react_native_pods.rb"

ENV['RCT_NEW_ARCH_ENABLED'] = "1";

prepare_react_native_project!

target 'rndfiddle-macOS' do
  project 'rndfiddle.xcodeproj'
  platform :macos, '14.0'
  use_expo_modules!

  config_command = [
    'npx',
    'expo-modules-autolinking',
    'react-native-config',
    '--json',
    '--platform',
    'ios'
  ]
  config = use_native_modules!(config_command)

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => react_native_macos_path,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer, react_native_macos_path)

    # https://github.com/facebook/react-native/issues/55601
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')

    if File.exist?(fmt_base)
    content = File.read(fmt_base)
      unless content.include?('Xcode 26 workaround')
        patched = content.gsub(
          /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
          "// Xcode 26 workaround: disable consteval\n\\1 0"
        )
        if patched != content
          File.chmod(0644, fmt_base)
          File.write(fmt_base, patched)
        end
      end
    end
  end
end
